apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  labels: {app: guestbook, tier: frontend}
spec:
  replicas: 2
  selector: {matchLabels: {app: guestbook, tier: frontend}}
  template:
    metadata: {labels: {app: guestbook, tier: frontend}}
    spec:
      containers:
      - name: ui
        image: gcr.io/google_samples/gb-frontend:v5
        ports: [{containerPort: 80}]
